apiVersion: v1
kind: Service
metadata:
  name: education-allocator 
  labels:
spec:
  type: LoadBalancer
  ports:
  - name: education-allocator 
    port: 80 
    targetPort: 5070 
  selector:
    name: education-allocator 
